// Merge request detection.
// discovers every open merge request as an `MR-<iid>` branch job and fills the environment

pipeline {
  agent any

  environment {
    GITLAB_URL     = 'http://gitlab.orb.local'
    GITLAB_PROJECT = 'root/mobivisor-console'
  }

  stages {
    stage('DocBot') {
      when { changeRequest() }
      steps {
        withCredentials([usernamePassword(credentialsId: 'gitlab-http',
                                          usernameVariable: 'GITLAB_USER',
                                          passwordVariable: 'GITLAB_TOKEN')]) {
          sh 'docbot'
        }
        archiveArtifacts artifacts: 'detection.json,mr.json', fingerprint: true
      }
    }
  }
}
